version: '3'
services:
  app:
    image: "node:20-alpine"
    user: "node"
    working_dir: "/home/node/app"
    ports:
      - 3000:3000
    volumes:
      - ./app:/home/node/app
    command: "npm start"